/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "DatabaseMigrator": {
      "name": string
      "type": "sst.aws.Function"
    }
    "MyBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MyDatabase": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "app-queue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "nx-ddd-vpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "nx-ddd-web-app": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "redis": {
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Redis"
      "username": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}